name: Check links

on:
  pull_request:
    branches: [main]
  # Add an option to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --no-progress
            --include-fragments
            --exclude-path ./themes/
            --exclude-path ./layouts/
            --exclude-path ./content/blog/nuttx-getting-started/
            .
          output: ./lychee_output.txt
          # Fail action on broken links
          fail: true

      - name: Check if lychee_output.txt exists
        run: |
          if [ -f "./lychee_output.txt" ]; then
            echo "lychee_output.txt file exists."
          else
            echo "lychee_output.txt file does not exist."
            exit 1
          fi

      - name: Print lychee_output.txt contents
        run: cat ./lychee_output.txt
        if: success() && steps.lychee.outputs.fail

      # - name: Upload Lychee Output
      #   if: failure()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: lychee-output
      #     path: ./lychee_output.txt

      # - name: Comment on PR with Link Check Results
      #   if: failure()
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const fs = require('fs');
      #       const output = fs.readFileSync('./lychee_output.txt', 'utf8');
      #       const failedLinks = output.match(/.*\[.*\]\(.*\).*/g).join('\n');
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: `Link Checker found the following broken links:\n\n${failedLinks}`
      #       });
