name: Check links

on:
  pull_request:
    branches: [main]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --no-progress
            --include-fragments
            --exclude-path ./themes/
            --exclude-path ./layouts/
            --exclude-path ./content/blog/nuttx-getting-started/
            .
          output: ./lychee_output.md
          # Fail action on broken links
          fail: true

      # - name: Check if lychee_output.md exists
      #   run: |
      #     if [ -f "./lychee_output.md" ]; then
      #       cat ./lychee_output.md
      #       echo 'there is error'
      #       exit 1
      #     else
      #       cat ./lychee_output.md
      #     fi

      - name: Notify
        if: failure()
        run: |
          echo "Please review the reported links.
          echo "If a link is valid but fails due to a CAPTCHA challenge, IP blocking, login requirements, etc.,
          consider adding such links to .lycheeignore file to bypass future checks."
