name: Check for RTFM

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-rtfm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Search for RTFM in PR changes
        run: |
          if git diff origin/main...HEAD | grep -iq "RTFM"; then
            echo "RTFM found in changes. Failing the job."
            exit 1
          else
            echo "No RTFM found in changes."
          fi
