name: Check links

on:
  pull_request:
    branches: [main]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: |
            --no-progress
            --include-fragments
            --exclude-path ./themes/
            --exclude-path ./layouts/
            .
          # Do not fail immediately on broken links
          fail: false

      - name: Check Link Checker Result
        id: result
        run: |
          if grep -q 'ERROR' .lychee/lychee.log; then
            echo "Link checking failed. Please address the broken links reported by the link checker. If you encounter links that work but fail due to CAPTCHA or other challenges, consider adding them to the .lycheeignore file."
            exit 1
          else
            echo "Link checking passed. No broken links found."
          fi
